// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDon3Jdjc1vYYTZAQvREXLkacTlFCo5Pak',
    appId: '1:646852870470:web:d9a13af86a5308fee2a547',
    messagingSenderId: '646852870470',
    projectId: 'matchhouse-ca5a8',
    authDomain: 'matchhouse-ca5a8.firebaseapp.com',
    storageBucket: 'matchhouse-ca5a8.firebasestorage.app',
    measurementId: 'G-J8X8VMDNH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC37tMlj3FmwVceRLtZuKC55q5uHsthn04',
    appId: '1:646852870470:android:ea7bf50edbb4b540e2a547',
    messagingSenderId: '646852870470',
    projectId: 'matchhouse-ca5a8',
    storageBucket: 'matchhouse-ca5a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUaOeXhwPuxEG-k0HpCq4qN7VRjp_n8Y4',
    appId: '1:646852870470:ios:06c400ef185f62aae2a547',
    messagingSenderId: '646852870470',
    projectId: 'matchhouse-ca5a8',
    storageBucket: 'matchhouse-ca5a8.firebasestorage.app',
    iosClientId: '646852870470-lht0q08mhhk4g2245sbugtbj3g9ju80e.apps.googleusercontent.com',
    iosBundleId: 'com.example.matchhouseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUaOeXhwPuxEG-k0HpCq4qN7VRjp_n8Y4',
    appId: '1:646852870470:ios:06c400ef185f62aae2a547',
    messagingSenderId: '646852870470',
    projectId: 'matchhouse-ca5a8',
    storageBucket: 'matchhouse-ca5a8.firebasestorage.app',
    iosClientId: '646852870470-lht0q08mhhk4g2245sbugtbj3g9ju80e.apps.googleusercontent.com',
    iosBundleId: 'com.example.matchhouseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDon3Jdjc1vYYTZAQvREXLkacTlFCo5Pak',
    appId: '1:646852870470:web:6106f58ec79baa1be2a547',
    messagingSenderId: '646852870470',
    projectId: 'matchhouse-ca5a8',
    authDomain: 'matchhouse-ca5a8.firebaseapp.com',
    storageBucket: 'matchhouse-ca5a8.firebasestorage.app',
    measurementId: 'G-6ZHHWF2S7J',
  );
}
